look/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('projects/', include('projects.urls'), name='projects'),
    path('mortgage/', include('mortgage.urls'), name='mortgage'),
    path('rent/', include('rent.urls'), name='rent'),
    path('trade_in/', include('trade_in.urls'), name='trade_in'),
    path('support/', include('support.urls'), name='support'),


    path('contact/', include('contact.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

look/contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ContactView.as_view, name='contact')
]

look/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.Search.as_view(), name='search'),
]

from django.contrib.flatpages import views
urlpatterns += [
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
]

look/contact/models.py
from django.db import models

class Contact(models.Model):
    email = models.EmailField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.email

look/home/models.py
# from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# from mptt.models import MPTTModel, TreeForeignKey


class Districts(models.Model):
    '''Районы'''
    image = models.ImageField(upload_to='districts/')
    name = models.CharField(max_length=50)
    description = models.TextField(null=True)
    places_nearbly = models.TextField(null=True)
    url = models.SlugField(unique=True)
    metro = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse("detail", kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Район'
        verbose_name_plural = 'Районы'

class DistrictsNews(models.Model):
    title = models.CharField(max_length=100)
    anons = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to='districts_news/', null=True, blank=True)
    date = models.DateField(null=True)
    districts = models.ForeignKey('Districts',
                                  verbose_name='Район',
                                  on_delete=models.CASCADE,
                                  null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новости'
        verbose_name_plural = 'Новости'


class Apartment(models.Model):
    apart_name = models.CharField(max_length=50, null=True)
    apart_image = models.ImageField(upload_to='districts_apart/', null=True)
    apart_price = models.CharField(max_length=50, null=True)
    districts = models.ForeignKey('Districts',
                                  verbose_name='Район',
                                  on_delete=models.CASCADE,
                                  null=True)

    def __str__(self):
        return self.apart_name

    class Meta:
        verbose_name = 'Планировка'
        verbose_name_plural = 'Планировки'

class DistrictsImage(models.Model):
    '''Фотографии районов'''
    name = models.CharField('Название', max_length=100)
    image = models.ImageField('Изображение', upload_to='districts_image/')
    description = models.TextField('Описание', null=True)
    slug = models.SlugField(max_length=100, null=True, unique=True)
    districts = models.ForeignKey('Districts',
                                  verbose_name='Район',
                                  on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Фотографии района'
        verbose_name_plural = 'Фотографии района'


class Category(models.Model):
    '''Категории'''
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'


class Reviews(models.Model):
    '''Отзывы'''
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    date = models.DateField('Дата', null=True)
    # parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    districts = models.ForeignKey('Districts',
                                  verbose_name='район',
                                  on_delete=models.CASCADE,
                                  null=True)

    def __str__(self):
        return f'{self.name} - {self.districts}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

look/contact/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from contact.models import Contact


class ContactForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Contact
        fields = ('email',)
        widgets = {
            'email': forms.TextInput(attrs={
                'class': 'editContent',
                'placeholder': 'Your Email...'
            })
        }
        labels = {
            'email': ''
        }

look/home/forms.py
from django import forms

from .models import Districts, Reviews
from django.forms import TextInput, DateTimeInput, Textarea

class DisctictsForm(forms.ModelForm):
    class Meta:
        model = Districts
        fields = ['image', 'name', 'url', 'metro', 'price', 'description']

class ReviewsForm(forms.ModelForm):
    '''Форма отзывов'''

    class Meta:
        model = Reviews
        fields = ('text', 'name', 'date',)
        # widgets = {
        #     'name': forms.TextInput(attrs={'class':'form-control border', 'placeholder': 'Name'}),
        #     'text': forms.Textarea(attrs={'class':'form-control border', 'placeholder': 'Your review...'})
        # }

look/contact/views.py
from django.shortcuts import render
from django.views.generic import CreateView

from contact.forms import ContactForm
from contact.models import Contact


class ContactView(CreateView):
    model = Contact
    form_class = ContactForm
    success_url = '/'

look/home/views.py
from django.shortcuts import render, redirect
# from django.views import View
from django.views.generic import DetailView, ListView
#
# from .forms import ReviewsForm

from .models import Districts, Category, DistrictsNews, DistrictsImage


def home(request):
    category = Category.objects.all()
    district = Districts.objects.all()
    return render(request, 'home/index.html', {'dist': district, 'cat': category})

class Search(ListView):
    context_object_name = 'projects'
    template_name = 'projects/projects.html'
    paginate_by = 2

    def get_queryset(self): # запрос в БД (с необходимыми свойствами)
        return Districts.objects.filter(url__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs): #переменные которые можно использовать в темплейтах, и добавить туда какие-то свои переменные
        context = super(Search, self).get_context_data(*args, **kwargs)
        context['q'] = f'q={self.request.GET.get("q")}&'
        return context

look/templates/home/contact.html
<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Contact - Alpha by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1><a href="index.html">Alpha</a> by HTML5 UP</h1>
					<nav id="nav">
						<ul>
							<li><a href="index.html">Home</a></li>
							<li>
								<a href="#" class="icon solid fa-angle-down">Layouts</a>
								<ul>
									<li><a href="generic.html">Generic</a></li>
									<li><a href="contact.html">Contact</a></li>
									<li><a href="elements.html">Elements</a></li>
									<li>
										<a href="#">Submenu</a>
										<ul>
											<li><a href="#">Option One</a></li>
											<li><a href="#">Option Two</a></li>
											<li><a href="#">Option Three</a></li>
											<li><a href="#">Option Four</a></li>
										</ul>
									</li>
								</ul>
							</li>
							<li><a href="#" class="button">Sign Up</a></li>
						</ul>
					</nav>
				</header>

			<!-- Main -->
				<section id="main" class="container medium">
					<header>
						<h2>Contact Us</h2>
						<p>Tell us what you think about our little operation.</p>
					</header>
					<div class="box">
						<form method="post" action="#">
							<div class="row gtr-50 gtr-uniform">
								<div class="col-6 col-12-mobilep">
									<input type="text" name="name" id="name" value="" placeholder="Name" />
								</div>
								<div class="col-6 col-12-mobilep">
									<input type="email" name="email" id="email" value="" placeholder="Email" />
								</div>
								<div class="col-12">
									<input type="text" name="subject" id="subject" value="" placeholder="Subject" />
								</div>
								<div class="col-12">
									<textarea name="message" id="message" placeholder="Enter your message" rows="6"></textarea>
								</div>
								<div class="col-12">
									<ul class="actions special">
										<li><input type="submit" value="Send Message" /></li>
									</ul>
								</div>
							</div>
						</form>
					</div>
				</section>

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">
						<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
						<li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
						<li><a href="#" class="icon brands fa-google-plus"><span class="label">Google+</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

look/templates/home/generic.html
<!DOCTYPE HTML>
{% load static recaptcha3 %}
<html>
	<head>
		<title>{{District.name}}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">

		{% recaptcha_init %}
		{% recaptcha_ready action_name='homepage' %}
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->

			{% include 'include/header_2.html' %}


			<!-- Main -->
				<section id="main" class="container">
					{% block content %}
					<header>
						<h2>{{detail.name}}</h2>
						<p>{{detail.description|safe}}</p>
					</header>

						<!-- Places nearby -->
						<section class="box special features">
							<header class="major">
								<span class="image feature"> <img src="{{detail.image.url}}" width="100%"></span>
								<h2>Places nearby</h2>
								<p>{{detail.places_nearbly}}</p>
							</header>
							<div class="features-row">
								{% for elem in detail.districtsimage_set.all %}
								<section>
									<span></span>
									<h3>{{elem.name}}</h3>
									<p><img src="{{ elem.image.url }}" class="image feature" width="100%" alt="">
										<a href="{% url 'dist_image' elem.slug %}" class="button primary">Learn more</a>
									</p><br>
								</section>
								{% endfor %}
							</div>
						</section>

						<!-- Apartment -->
						<section class="box special features">
							<h2>Choose an apartment:</h2>
							<div class="features-row">
								{% for elem in detail.apartment_set.all %}
								<section>
									<img src="{{elem.apart_image.url}}" class="image" width="80%">
									<h3>{{elem.apart_name}}: {{elem.apart_price}}
										<p><a class="button alt " style="height:20%;width:50%">Buy!</a></p>
									</h3><br>
								</section>
								{% endfor %}
							</div>
						</section>

						<!-- District news -->
						<section class="box special features">
							<h2>Project news:</h2>
							<div class="features-row">
								{% for elem in detail.districtsnews_set.all %}
								<section>
									<h3>{{elem.title}}</h3>
									<p>{{elem.anons}}</p>
									<h1>{{elem.date}}</h1>
									<p><a href="{% url 'dist_news' elem.id %}" class="button primary"
										  style="height:20%;width:50%">Learn
										more</a></p>
									<br>
								</section>
								{% endfor %}
							</div>
						</section>

						<!-- Review form -->
						<section class="box special features">
							<h2>Reviews</h2>
							<div class="features-row">
								<form action="{% url 'add_review' detail.id %}" method="post"><br>
									{% csrf_token %}
									<textarea style="resize: none" class="form-control" name="text"
											  placeholder="Your review..."></textarea><br>
									<input class="form-control" name="name" type="text" placeholder="Name"><br>
									<input class="form-control" name="date" type="date" placeholder="Date"><br><br>
									{{form.captcha}}
									<button class="button" type="submit">Send</button>
								</form>
								<!-- Reviews -->
								{% for elem in detail.reviews_set.all %}
								<div class="features-row">
									<br>
									<p>{{elem.text}}</p>
									<p>{{elem.name}}&nbsp;|&nbsp;{{elem.date}}</p>
								</div>
								{% endfor %}
							</div>
						</section>
					{% endblock content %}
				</section>
		</div>



			<!-- Footer -->
			{% include 'include/footer.html' %}


		<!-- Scripts -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
		<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
		<script src="{% static 'js/browser.min.js' %}"></script>
		<script src="{% static 'js/breakpoints.min.js' %}"></script>
		<script src="{% static 'js/util.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

look/templates/home/index.html
{% load static %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Alpha Сonstruction</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">

	</head>
	<body class="landing is-preload">
		<div id="page-wrapper">

			<!-- Header -->

			{% include 'include/header.html' %}

			<!-- Banner -->
				<section id="banner">
					<h2>Alpha</h2>
					<p>We don't build houses, we build the world</p>
					<ul class="actions special">
						<li><a href="#" class="button primary">Sign Up</a></li>
						<li><a href="{% url 'about' %}" class="button">About us</a></li>
					</ul>
				</section>

			<!-- Main -->
				<section id="main" class="container">

					<section class="box special">
						<header class="major">
							<h2>Think about the future
							<br />
								appreciate the present</h2>
							<p>We build houses based on modern architectural and construction solutions and uniform internal standards, we comply with the declared quality and construction deadlines.</p>
						</header>
						<span class="image featured"><img src="media/home_2.jpg" alt="building" /></span>
					</section>

					<section class="box special features">
						<div class="features-row">
							<section>
								<span class="icon solid major fas fa-angle-double-up accent2"></span>
								<h3>Speed</h3>
								<p>
									Alpha is a team of professionals who improve the created product on a daily basis,
									investing the accumulated knowledge and energy. Extensive experience, technological design, high organization and optimization of production processes allow us to build quickly and deliver houses on time or earlier.</p>
							</section>
							<section>
								<span class="icon solid major fa-thumbs-up accent3"></span>
								<h3>Quality</h3>
								<p>Our specialists constantly study the novelties of the construction market and choose advanced solutions that are applicable in our climatic conditions and realities.
									We attract proven contractors, like-minded people who support our principles, standards and production culture in order to build objects that meet the expectations of customers.</p>
							</section>
						</div>
						<div class="features-row">
							<section>
								<span class="icon solid major fa-university accent4"></span>
								<h3>Architecture</h3>
								<p>There are no insignificant details in the creation of housing — they form the architecture of life. We find points of development, build an aesthetic modern urban environment and work according to the same quality standards of objects for the comfort of our customers.</p>
							</section>
							<section>
								<span class="icon solid major fa-code-branch accent5"></span>
								<h3>Technologies</h3>
								<p>Alpha is an innovator with a rational approach. We use both classic and new
									technologies that meet the parameters of durability and energy efficiency that appear on the market. We implement BIM-design, digitalization of engineering systems and home management using a mobile application.</p>
							</section>
						</div>
					</section>
				</section>

			<!-- CTA -->


			<!-- Footer -->
				{% include 'include/footer.html' %}

		</div>

		<!-- Scripts -->
		{% include 'include/scripts.html' %}

	</body>
</html>